#Atividade somando numeros flutuantes
numero1 = float (input("insira o primeiro numero: "))
numero2 = float (input("insira o segundo numero: "))
soma = numero1+numero2
print ("a soma dos valores é: ",soma)
# atividade media de alunos
nota1 = float (input("insira a primeira nota: "))
nota2 = float (input("insira a segunda nota: "))
nota3 = float (input("insira a terceira nota: "))
nota4 = float (input("insira a quarta nota: "))
media = (nota1+nota2+nota3+nota4) /4
print ("a media dos alunos é: ",media)

