numero1 = float(input("insira o primeiro numero: "))
numero2 = float(input("insira o segundo numero: "))
soma = numero1+numero2
print("a soma dos dois numeros é:", soma)
#media de quatro notas dos alunos.
nota1 = float(input("insira a primeira nota:"))
nota2 = float(input("insira a segundanota:"))
nota3 = float(input("insira a terceira nota:"))
nota4 = float(input("insira a quarta nota:"))
media = (nota1+nota2+nota3+nota4) /4
print("a media das notas no total é:" ,media)